### ISSUE TITLE
Is VA Court Statewide Search data available or does it need to be crawled locally first?

### ISSUE THREAD

**Issue by fj** [openva/attorney-analysis#1]
This should amount to an inner join on two giant tables -- one from the cases CSV in `openva/attorney-analysis`, the other from the VA court system -- on the parameters specified in the README. Each record in the result set is a case which is in the cases CSV. If a case is in `openva/attorney-analysis` but not the result set, then there was no match for that case.

So, three questions:
- Can `https://github.com/Code4HR/va-circuit-court-search` be run in an automated way that extracts all the data for every circuit court to a usable form (e.g. a CSV like the one described)?
- Is this in violation of any rules or TOS for accessing the court system?
- Does this dataset already exist?

**Comment by waldoj** [comment]
Nope, it's not in violation of any TOS or rules. @bschoenfeld, could you speak to the question of the scraping output? That is, is there a big dataset that can just be downloaded? Or does one need to actually run your program, generate the scraped dataset, and _then_ use that data?

**Comment by bschoenfeld** [comment]
The only dataset of complete records that I am aware of is from 2014 and it is actually incomplete because I know that my scraper wasn't able to deduce all the case numbers. I have another dataset of case numbers and names that should be a complete record of everything on the Circuit Court website through 2014. Is that enough data for this project?

I have heard that the Circuit Court released bulk data as recently as last year, but I haven't ever seen that and I may be wrong about what it contains. I'll check.

The case numbers were collected with the intent of using them to collect detailed case information, but I haven't gotten to work on it in some time. I also don't have a good way to keep it all updated. My ultimate goal is to encourage the court to give us the bulk data.

**Comment by waldoj** [comment]
> I have another dataset of case numbers and names that should be a complete record of everything on the Circuit Court website through 2014. Is that enough data for this project?

Is it _only_ case numbers and names, or is it complete case data that includes that data? If the latter, I believe it'll get things most of the way to completion!

How does Virginia Circuit Court Search work, then? I assumed it was scraping the contents of all of the records into Mongo, and the API was querying against that Mongo instance. Is that not right?

**Comment by fj** [comment]
@bschoenfeld, does your dataset include at least the same fields (either directly or by inference) as the six fields in the dataset mentioned in the [README](https://github.com/openva/attorney-analysis/blob/master/README.md) here?

For example, I wouldn't expect courts to store their own FIPS data -- but if the case records you have mention what county they're from it should be easy to map it to the FIPS codes. But we need to be able to determine or generate the value for each field.

**Comment by bschoenfeld** [comment]
@waldoj The complete dataset is case number, name, charge, locality (county or city), current status, and next hearing or disposition date. The search works by scraping in real time. It's simply a tool to automate a process that journalists were doing manually. I adapted the scraper to try and collect all the data once I realized how valuable it could be in bulk. This project is proof that I should keep going.

@fj I just dove into your README and I don't think we have enough data yet. That being said, we can get it. The site doesn't give you any attorney information, but I did a quick analysis of my 2014 records where I have all the data and found that 93% of the time, having the court, the filing date, and the deposition date yields a unique name. 5% of the time, you get exactly two names.

**Comment by waldoj** [comment]
> The search works by scraping in real time.

Oh, interesting—I didn't realize that was how it worked. I appreciate that it's rather less demanding to scrape search results than to try to scrape _everything._

> I did a quick analysis of my 2014 records where I have all the data and found that 93% of the time, having the court, the filing date, and the deposition date yields a unique name. 5% of the time, you get exactly two names.

That's great! I'd expected a lower rate of duplicates (maybe 2%), but 5% is awfully good. I'll check with the ACLU of VA's Rob Poggenklass (who isn't a GitHub user, but should be following this conversation here) about the utility of having that 2014 data. My guess is that it'd be a whole lot better than nothing, which is what they've got right now. :)

**Comment by fj** [comment]
Cool, thanks @bschoenfeld -- it sounds like that's good enough, then. Can you make whatever data you have available? I'll sort out the data differences as best as I can.

**Comment by bschoenfeld** [comment]
Sure. The data is available as a CSV download on this page.

http://vacircuitcourtsearch.com/opendata

**Comment by bschoenfeld** [comment]
@fj Hopefully you've been following the other issues in this repo, but just in case - we realized that the anonymous data comes from the district courts, not the circuit courts. The link I left above is useless for this project and I haven't ever collected district court data.

**Comment by fj** [comment]
Oh, shoot. That explains why I wasn't really having any luck. Do we have any way to get the district court data?

**Comment by bschoenfeld** [comment]
Yeah. Check #4
