### ISSUE TITLE
Bad FIPS Codes in Data

### ISSUE THREAD

**Issue by bschoenfeld** [openva/attorney-analysis#3]
The following FIPS codes are found in the 2014 data, but as far as I can tell, the codes are invalid. I checked two separate lists and could not find these codes.

```
Bad FIPS Codes [701, 702, 711, 761, 762]
```

**Comment by waldoj** [comment]
Interesting—this might just be a mistake on the part of the courts, who provided this data. My guess is that there's nothing to be done, and those records will have to be ignored. :-/

**Comment by rpogge** [comment]
701 is Newport News General District Court (Criminal). 702 is Newport News GDC (Traffic). 711 is Norfolk GDC (Criminal). (712, though you didn't mention it, is Norfolk GDC (Traffic).) 761 is Richmond GDC (Criminal), and 762 is Richmond GDC (Traffic). Some of the larger district courts split their dockets this way. I'm using a list from the Supreme Court Office of the Executive Secretary.

**Comment by waldoj** [comment]
Thank you, @rpogge! (And welcome to GitHub. :)

**Comment by bschoenfeld** [comment]
@rpogge answered this, but I also realized you can find all these codes in the HTML on the District Court's case information system. The script I wrote in #4 pulls the codes from there.
