### ISSUE TITLE
Tracking Output

### ISSUE THREAD

**Issue by waldoj** [openva/attorney-analysis#8]
I'm creating a ticket where we can report on progress.

2013 just finished and [I just synced it with this repo](https://github.com/openva/attorney-analysis/blob/master/cases/2013_matched.csv). 2011 is underway. (Unfortunately, there was no way to keep that from syncing with Git, so I have a 2011 file added that has just a couple of lines in it.) @bschoenfeld, would you mind adding in your output, too? That way @rpogge can start to use and use the output.

This seems to be going very well! Thanks for all of your work on this, @bschoenfeld. :)

**Comment by bschoenfeld** [comment]
Added 2014 and 41 of 273 in 2012. Glad to help!

**Comment by waldoj** [comment]
Added all of 2011.

**Comment by waldoj** [comment]
I'm moving onto 2010 now.

**Comment by waldoj** [comment]
Oops, I see that's done. 2009 it is.

**Comment by waldoj** [comment]
2009 finished.

**Comment by waldoj** [comment]
Are we..._done_? That's everything, isn't it?

**Comment by bschoenfeld** [comment]
Looks that way.

**Comment by waldoj** [comment]
Well, @rpogge—[here are the matched records](https://github.com/openva/attorney-analysis/tree/master/cases). Does that do the trick for you?

**Comment by rpogge** [comment]
I will take a look tomorrow and let you know. Many thanks!

**Comment by rpogge** [comment]
I've looked at the first few, and things look very good. Not only did you get the matches, but it appears that the data set I had was incomplete. Your scripts managed to uncover at least one additional case that matched the criteria but was not in the data set. I suspect there will be more. And on the substance of what I'm looking for -- one of the first cases I looked at appears to be one in which the defendant got (suspended) jail time without a lawyer.

I really can't thank this group enough. I'll continue to work through the results and let you know if I run into any problems.

**Comment by rpogge** [comment]
@bschoenfeld Line 12 of 2010_matched appears to be an error. That defendant had an attorney.

Ahh, but Line 13 has the right data, just a different defendant. Not a big problem after all.

**Comment by bschoenfeld** [comment]
@rpogge I never actually checked the attorney field on the website because I couldn't figure out how dependable that data was. It seemed possible that the field was empty when it shouldn't have been. Let me know if you run across that too many more times and we can modify and re-run.

**Comment by rpogge** [comment]
For the rows in which the case number and name fields are blank, am I to presume that the script found no such case?

**Comment by bschoenfeld** [comment]
That is correct. I'm wondering if its possible a case was concluded without
a hearing. If that occurred, we would have missed it. We could have missed
it if the offense code didn't match up, but that seemed unlikely to me.
